FROM node:20-alpine3.18
WORKDIR /usr/local/apps/myapp

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/myapp/dev
COPY tsconfig.json ./

COPY src ./src
COPY public ./public
COPY astro.config.mjs ./
COPY .env ./

EXPOSE ${PORT}

RUN npm run build
CMD ["npm", "run", "dev", "--host"]