name = "dilago"
compatibility_date = "2025-07-07"

[vars]
SUPABASE_URL = "https://wqcvevghjaltsbepieaj.supabase.co"
EMAIL_DESTINO = "fibra.dilago@gmail.com"  # Correo de backup

# Variables secretas que deben configurarse en Cloudflare:
# SUPABASE_SERVICE_ROLE_KEY: Settings -> Variables and Secrets
# RESEND_API_KEY: Settings -> Variables and Secrets
